version: 2
jobs:
  build:
    docker:
      - image: gregbreen/uncannier-thunderboard:gecko-sdk-suite-v2.5
    steps:
      - checkout
      - run:
          name: Build the Uncannier Thunderboard Sense 2 bootloader
          command: /opt/SimplicityStudio_v4/studio -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild --launcher.suppressErrors -import uts-bootloader -cleanBuild uts-bootloader/Release
      - run:
          name: Build the Uncannier Thunderboard Sense 2 application - Debug configuration
          command: /opt/SimplicityStudio_v4/studio -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild --launcher.suppressErrors -import uts-application -cleanBuild uts-application/Debug
      - run:
          name: Build the Uncannier Thunderboard Sense 2 application - Release configuration
          command: /opt/SimplicityStudio_v4/studio -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild --launcher.suppressErrors -import uts-application -cleanBuild uts-application/Release
      - run:
          name: Build the Uncannier Thunderboard Sense 2 application - Test configuration
          command: /opt/SimplicityStudio_v4/studio -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild --launcher.suppressErrors -import uts-application -cleanBuild uts-application/Test
      - run:
          name: Generate xUnit-compatible test output
          command: mkdir -p JUnit; uts-application/Test/uts-application -ojunit; mv cpputest*.xml JUnit
      - run:
          name: Package the build binaries
          command: |
            cd uts-application/Release
            mv uts-image.hex uts-image-$CIRCLE_BUILD_NUM.hex
            mv uts-application.gbl uts-application-$CIRCLE_BUILD_NUM.gbl
            mv uts-apploader.gbl uts-apploader-$CIRCLE_BUILD_NUM.gbl
            tar -cvzf uncannier-thunderboard-sense2.tar.gz uts-image-$CIRCLE_BUILD_NUM.hex uts-application-$CIRCLE_BUILD_NUM.gbl uts-apploader-$CIRCLE_BUILD_NUM.gbl
      - store_test_results:
          path: ./JUnit
      - store_artifacts:
          path: ./uts-application/Release/uncannier-thunderboard-sense2.tar.gz
          destination: uncannier-thunderboard-sense2.tar.gz
      - store_artifacts:
          path: ./uts-application/Test/Coverage
          destination: Coverage

