// Copyright 2019 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_device_name                      3
#define gattdb_board_serial                    16
#define gattdb_board_rev                       18
#define gattdb_firmware_rev                    20
#define gattdb_system_id                       22
#define gattdb_batt_measurement                25
#define gattdb_es_uvindex                      29
#define gattdb_es_pressure                     31
#define gattdb_es_temperature                  33
#define gattdb_es_humidity                     35
#define gattdb_es_ambient_light                37
#define gattdb_es_sound_level                  39
#define gattdb_es_control_point                41
#define gattdb_ota_control                     45
#define gattdb_power_source_type               48
#define gattdb_iaq_eco2                        51
#define gattdb_iaq_tvoc                        53
#define gattdb_iaq_control_point               55
#define gattdb_ui_buttons                      59
#define gattdb_ui_leds                         61
#define gattdb_ui_rgbleds                      64
#define gattdb_ui_control_point                67
#define gattdb_aio_digital_in                  71
#define gattdb_aio_digital_out                 76
#define gattdb_imu_acceleration                81
#define gattdb_imu_orientation                 84
#define gattdb_imu_control_point               87
#define gattdb_hall_state                      91
#define gattdb_hall_field_strength             94
#define gattdb_hall_control_point              97

#endif
