// Copyright 2019 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_device_name                      3
#define gattdb_board_serial                    16
#define gattdb_board_rev                       18
#define gattdb_software_rev                    20
#define gattdb_firmware_rev                    22
#define gattdb_system_id                       24
#define gattdb_batt_measurement                27
#define gattdb_es_uvindex                      31
#define gattdb_es_pressure                     33
#define gattdb_es_temperature                  35
#define gattdb_es_humidity                     37
#define gattdb_es_ambient_light                39
#define gattdb_es_sound_level                  41
#define gattdb_es_control_point                43
#define gattdb_ota_control                     47
#define gattdb_power_source_type               50
#define gattdb_iaq_eco2                        53
#define gattdb_iaq_tvoc                        55
#define gattdb_iaq_control_point               57
#define gattdb_ui_buttons                      61
#define gattdb_ui_leds                         63
#define gattdb_ui_rgbleds                      66
#define gattdb_ui_control_point                69
#define gattdb_aio_digital_in                  73
#define gattdb_aio_digital_out                 78
#define gattdb_imu_acceleration                83
#define gattdb_imu_orientation                 86
#define gattdb_imu_control_point               89
#define gattdb_hall_state                      93
#define gattdb_hall_field_strength             96
#define gattdb_hall_control_point              99

#endif
